# Generated by Django 5.0.6 on 2024-06-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='online-pharmacy\\media\\profile_pics\\default.jpg', upload_to='profile_pics/'),
        ),
    ]
