# Generated by Django 5.0.6 on 2024-06-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Pharmacist', 'Pharmacist')], default='Customer', max_length=50),
        ),
    ]
