# Generated by Django 5.0.6 on 2024-06-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_userprofile_area_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/default.jpg', upload_to='shop/images'),
        ),
    ]
